name: ems_v4
description: "employee management system"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  get: ^4.6.6
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  auto_route_generator: ^7.3.2
  lottie: ^2.7.0
  flutter_device_type: ^0.4.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hdf/
    - assets/lottie/
    - assets/svg/
    - assets/map_style.txt
    - assets/json/