name: ems_v4
description: "employee management system"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  get: ^4.6.6
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  auto_route_generator: ^7.3.2
  lottie: ^2.7.0
  flutter_device_type: ^0.4.0
  loading_animation_widget: ^1.2.0+4
  calendar_date_picker2: ^0.5.3
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  launcher_name: ^1.0.2
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_geocoding_api: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ems_icon_nobg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ems_icon_nobg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ems_icon_nobg.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ems_icon_nobg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hdf/
    - assets/lottie/
    - assets/svg/
    - assets/map_style.txt
    - assets/json/